<<<<<<< HEAD
=======
version: '3.8'

>>>>>>> 93a86bcb04ca010b2ae1e08f121dda4fc06575ca
services:
  app:
    build: .
    container_name: ai_consultant_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - qdrant
<<<<<<< HEAD
      - ollama
    volumes:
      - ./documents:/data

  ollama:
    image: ollama/ollama:latest
    container_name: ai_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

=======
    volumes:
      - ./documents:/data

>>>>>>> 93a86bcb04ca010b2ae1e08f121dda4fc06575ca
  db:
    image: postgres:15
    container_name: ai_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: ai_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
<<<<<<< HEAD
  qdrant_data:
  ollama_data:
=======
  qdrant_data:
>>>>>>> 93a86bcb04ca010b2ae1e08f121dda4fc06575ca
